# Generated by Django 4.2.8 on 2023-12-05 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0048_parametersetbarrier_parameter_set_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='avatar_animation_speed',
            field=models.DecimalField(decimal_places=2, default=0.67, max_digits=3, verbose_name='Animation Speed'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='avatar_move_speed',
            field=models.DecimalField(decimal_places=1, default=5.6, max_digits=3, verbose_name='Move Speed'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='avatar_scale',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3, verbose_name='Avatar Scale'),
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_events', to='main.session'),
        ),
    ]
