# Generated by Django 4.2.8 on 2023-12-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_parameterset_avatar_animation_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetplayer',
            name='id_label',
            field=models.CharField(default='1', max_length=20, verbose_name='ID Label'),
        ),
    ]
