# Generated by Django 4.2.8 on 2023-12-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_parametersetplayer_id_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='tokens_per_period',
        ),
    ]
