# Generated by Django 4.2.8 on 2023-12-06 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_parameterset_tokens_per_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default='Info Here', max_length=100, null=True, verbose_name='Info')),
                ('x', models.IntegerField(default=50, verbose_name='Location X')),
                ('y', models.IntegerField(default=50, verbose_name='Location Y')),
                ('width', models.IntegerField(default=50, verbose_name='Width')),
                ('height', models.IntegerField(default=50, verbose_name='Height')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_fields', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Field',
                'verbose_name_plural': 'Parameter Set Fields',
                'ordering': ['id'],
            },
        ),
    ]
