# Generated by Django 4.2.8 on 2023-12-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_parametersetfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='disc_build_length',
            field=models.IntegerField(default=12, verbose_name='Disc Build Length'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='field_build_length',
            field=models.IntegerField(default=12, verbose_name='Field Build Length'),
        ),
    ]
