# Generated by Django 4.2.8 on 2023-12-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_parameterset_build_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_pr', models.BooleanField(default=True, verbose_name='Field Property Rights')),
                ('seed_pr', models.BooleanField(default=True, verbose_name='Seed Property Rights')),
                ('disc_pr', models.BooleanField(default=True, verbose_name='Disc Property Rights')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('help_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_notices', to='main.helpdocssubject')),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_periods', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Period',
                'verbose_name_plural': 'Parameter Set Periods',
                'ordering': ['id'],
            },
        ),
    ]
