# Generated by Django 4.2.8 on 2023-12-13 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_parametersetperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='parameter_set_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_periods', to='main.parametersetperiod'),
        ),
    ]
