# Generated by Django 4.2.8 on 2023-12-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_sessionperiod_parameter_set_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='disc_value',
            field=models.IntegerField(default=10, verbose_name='Disc Value'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='seed_multipiers',
            field=models.TextField(blank=True, default='3.5', verbose_name='Seed Multipliers'),
        ),
    ]
