# Generated by Django 4.2.9 on 2024-01-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_rename_seed_multipiers_parameterset_seed_multipliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='interaction_only_length',
            field=models.IntegerField(default=30, verbose_name='Interaction Only Length'),
        ),
    ]
