# Generated by Django 4.2.9 on 2024-01-16 20:52

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_parameterset_interaction_only_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='summary_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Summary Data'),
        ),
    ]
