# Generated by Django 4.2.9 on 2024-01-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_parameterset_seed_build_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ['period_number', '-time_remaining', 'timestamp'], 'verbose_name': 'Session Event', 'verbose_name_plural': 'Session Events'},
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_chat',
            field=models.IntegerField(default=6, verbose_name='Required Action: Chat'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_disc',
            field=models.IntegerField(default=2, verbose_name='Required Action: Disc'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_field',
            field=models.IntegerField(default=4, verbose_name='Required Action: Move'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_interaction',
            field=models.IntegerField(default=5, verbose_name='Required Action: Move'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_move',
            field=models.IntegerField(default=1, verbose_name='Required Action: Move'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_seed',
            field=models.IntegerField(default=3, verbose_name='Required Action: Seed'),
        ),
    ]
