# Generated by Django 4.2.9 on 2024-02-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_instructionset_action_page_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='enable_discs',
            field=models.BooleanField(default=True, verbose_name='Enable Discs'),
        ),
    ]
