# Generated by Django 4.2.11 on 2024-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_session_id_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayer',
            name='enable_disc_production',
            field=models.BooleanField(default=True, verbose_name='Enable Disc Production'),
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='enable_field_production',
            field=models.BooleanField(default=True, verbose_name='Enable Field Production'),
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='enable_seed_production',
            field=models.BooleanField(default=True, verbose_name='Enable Disc Seed'),
        ),
    ]
