# Generated by Django 4.2.11 on 2024-05-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_parametersetplayer_enable_disc_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayer',
            name='instruction_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_players_c', to='main.instructionset'),
        ),
    ]
