# Generated by Django 4.2.11 on 2024-05-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_parametersetplayer_instruction_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='instruction_set',
        ),
        migrations.AlterField(
            model_name='parametersetplayer',
            name='hex_color',
            field=models.CharField(default='0x000000', max_length=30, verbose_name='Hex Color'),
        ),
    ]
