# Generated by Django 4.2.13 on 2024-07-30 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_session_replay_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'base_manager_name': 'objects', 'ordering': ['-start_date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
