{%include "subject/subject_home/the_stage/pixi_setup.js"%}
{%include "subject/subject_home/the_stage/avatar.js"%}
{%include "subject/subject_home/the_stage/helpers.js"%}
{%include "subject/subject_home/the_stage/text_emitter.js"%}
{%include "subject/subject_home/the_stage/transfer_beam.js"%}
{%include "subject/subject_home/the_stage/wall.js"%}
{%include "subject/subject_home/the_stage/move_objects.js"%}
{%include "subject/subject_home/the_stage/barriers.js"%}
{%include "subject/subject_home/the_stage/ground.js"%}
{%include "subject/subject_home/the_stage/field.js"%}
{%include "subject/subject_home/the_stage/destroy.js"%}